### PR TITLE
Indent tidy

### PR DESCRIPTION
**Pull request by RebDugNZ**

### CODE REVIEW

**Comment by anthony-gordon** [comment]
Everything looks perfect! I'm going to go ahead and merge.

**Comment by anthony-gordon** [comment]
Actually maybe I can't it says only those with write access to this repository can merge pull requests? maybe I'm misunderstanding the assignment? It says I have to delete your tidying branch. Can you do that to mine if you think the changes were ok and let me know how that went? thanks :)

**Comment by RebDugNZ** [comment]
Hey so hopefully setting you as a collaborator will let you merge :)

**Comment by anthony-gordon** [comment]
http://anthony-gordon.github.io/blog/t3-design-to-web-blog.html

**Pull request merged**
